
FROM python:3.11
WORKDIR /app/backend



RUN apt-get update; apt-get -y install python3.11 python3-pip python3.11-venv
# RUN python3.11 -m venv .venv && /app/.venv/bin/python -m pip install flask
RUN python3 -m venv /app/backend/venv
COPY . .
# 设置环境变量
ENV PATH="/app/backend/venv/bin:$PATH"

ENV PYTHONPATH "${PYTHONPATH}:/app/backend"


COPY requirements.txt .
RUN pip install -r requirements.txt 

RUN git clone https://github.com/spack/spack.git /spack
RUN git clone https://github.com/robertu94/spack_packages robertu94

# 设置环境变量以使用Spack
ENV SPACK_ROOT=/spack
ENV PATH=${SPACK_ROOT}/bin:${PATH}


# 初始化Spack环境并安装包
RUN . ${SPACK_ROOT}/share/spack/setup-env.sh && \
    spack repo add robertu94 && \
    spack install libpressio+python+sz3+zfp+fpzip+mgard ^openblas~fortran

# RUN echo "spack load libpressio && exec your-command-here" > /start.sh



ENV PYTHONPATH "${PYTHONPATH}:/app/backend/venv/lib/python3.11/site-packages"

COPY . .

RUN echo "#!/bin/bash" > /start.sh
RUN echo ". ${SPACK_ROOT}/share/spack/setup-env.sh && spack load libpressio && python3 ./src/components/main.py" >> /start.sh
RUN chmod +x /start.sh


# 使用启动脚本作为容器的默认命令
EXPOSE 5000
CMD ["/start.sh"]

# CMD ["python3", "src/components/main.py"]
 
# 第二阶段：构建 Python 部分
